import pandas as pd
import os
import matplotlib.pyplot as plt

def analyze_newspaper_changes(csv_path, output_dir):
    """
    Analyzes the total number of articles, total changes, and the breakdown
    of changes by classification (typo/content change) for each newspaper.
    Also generates a plot visualizing the change breakdown.

    Args:
        csv_path (str): Path to the input CSV file generated by export_to_csv.py.
        output_dir (str): Directory to save the plot image.
    """
    if not os.path.exists(csv_path):
        print(f"Error: CSV file not found at '{csv_path}'")
        print("Please run 'src/export_to_csv.py' first to generate the data.")
        return

    print(f"Reading data from '{csv_path}' for analysis...")
    df = pd.read_csv(csv_path)

    os.makedirs(output_dir, exist_ok=True)

    total_articles_per_newspaper = df.groupby('newspaper_name')['article_title'].nunique().reset_index()
    total_articles_per_newspaper.rename(columns={'article_title': 'total_articles'}, inplace=True)

    total_changes_per_newspaper = df.groupby('newspaper_name').size().reset_index(name='total_changes')

    typo_changes_per_newspaper = df[df['classification'] == 'typo'].groupby('newspaper_name').size().reset_index(name='typo_changes')

    content_changes_per_newspaper = df[df['classification'] == 'content change'].groupby('newspaper_name').size().reset_index(name='content_changes')

    analysis_df = total_articles_per_newspaper.merge(total_changes_per_newspaper, on='newspaper_name', how='left')
    analysis_df = analysis_df.merge(typo_changes_per_newspaper, on='newspaper_name', how='left').fillna(0)
    analysis_df = analysis_df.merge(content_changes_per_newspaper, on='newspaper_name', how='left').fillna(0)

    analysis_df['typo_changes'] = analysis_df['typo_changes'].astype(int)
    analysis_df['content_changes'] = analysis_df['content_changes'].astype(int)

    print("\n--- Newspaper Change Analysis ---")
    print(analysis_df)
    print("\nAnalysis complete.")
    print(analysis_df.sum())

    # --- Plot: Breakdown of Changes by Newspaper ---
    print("Generating plot: Breakdown of Changes by Newspaper...")
    plt.style.use('seaborn-v0_8-whitegrid')
    fig, ax = plt.subplots(figsize=(12, 8))

    # Prepare data for stacked bar chart
    plot_df = analysis_df.set_index('newspaper_name')[['typo_changes', 'content_changes']]
    
    # Create the stacked bar chart
    plot_df.plot(kind='barh', stacked=True, ax=ax, color=['lightcoral', 'lightskyblue'])

    # Add total change counts to the end of each bar
    # We sort the analysis_df by newspaper_name to match the plot's order
    sorted_analysis_df = analysis_df.sort_values('newspaper_name', ascending=False)
    for i, total in enumerate(sorted_analysis_df['total_changes']):
        ax.text(total + 0.2, i, str(total), va='center', fontweight='bold', fontsize=16)

    ax.set_title('Breakdown of Article Changes by Newspaper', fontsize=20)
    ax.set_xlabel('Number of Changes', fontsize=18)
    ax.set_ylabel('Newspaper', fontsize=18)
    ax.legend(title='Change Type', fontsize=16)
    ax.tick_params(axis='both', which='major', labelsize=16)
    plt.tight_layout()

    plot_path = os.path.join(output_dir, 'change_breakdown_by_newspaper.png')
    plt.savefig(plot_path)
    print(f"Saved plot to '{plot_path}'")
    plt.close(fig)

    # --- Plot: Grouped Bar Chart of Articles and Changes ---
    print("Generating plot: Article & Change Counts by Newspaper...")
    fig, ax = plt.subplots(figsize=(16, 8))

    # Prepare data for grouped bar chart
    plot_df_grouped = analysis_df.set_index('newspaper_name')[['total_articles', 'typo_changes', 'content_changes']]

    # Create the grouped bar chart
    plot_df_grouped.plot(kind='bar', ax=ax, color=['mediumseagreen', 'lightcoral', 'lightskyblue'])

    ax.set_title('Total Articles vs. Change Types by Newspaper', fontsize=24)
    ax.set_xlabel('Newspaper', fontsize=22)
    ax.set_ylabel('Count', fontsize=22)
    ax.legend(title='Metric', fontsize=18)
    plt.xticks(rotation=45, ha='right', fontsize=20)
    plt.yticks(fontsize=22)
    plt.tight_layout()

    grouped_plot_path = os.path.join(output_dir, 'article_and_change_counts_by_newspaper.png')
    plt.savefig(grouped_plot_path)
    print(f"Saved plot to '{grouped_plot_path}'")
    plt.close(fig)


if __name__ == "__main__":
    # The CSV file is assumed to be in the project's root directory
    CSV_FILE = 'article_changes_export.csv'
    IMAGE_DIR = 'images'

    analyze_newspaper_changes(CSV_FILE, IMAGE_DIR)